---
{{ if .Values.install.digitalTwin }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.digitalTwin.docker.secret.name  | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:traceability-irs/data/dev/aasregistry#dockerpullsecret>

{{ end }}