registry:
  enableKeycloak: false
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 1Gi
      resources:
        limits:
          cpu: 750m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi

  registry:
    authentication: true
    idpIssuerUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central
    host: irs-aas-registry-test.dev.demo.catena-x.net
    ingress:
      enabled: true
      tls: true
      className: nginx
      urlPrefix: /
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: /

    resources:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
