# #############################################################################
  # Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
  #
  # See the NOTICE file(s) distributed with this work for additional
  # information regarding copyright ownership.
  #
  # This program and the accompanying materials are made available under the
  # terms of the Apache License, Version 2.0 which is available at
  # https://www.apache.org/licenses/LICENSE-2.0.
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  # License for the specific language governing permissions and limitations
  # under the License.
  #
  # SPDX-License-Identifier: Apache-2.0
  # #############################################################################
---

{{- $vaultToken := .Values.vault.server.dev.devRootToken -}}
{{- $vaultHosts := (index .Values.vault.server.ingress.hosts 0) -}}
{{- $vaultUrl := printf "%s%s" "https://" $vaultHosts.host -}}
{{- $fullName := include "vault.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-post-install-vault-setup
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "alpine:3.19"
          imagePullPolicy: "IfNotPresent"
          command:
            - "/bin/sh"
            - "-c"
            - |
              sleep 10

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/key.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-dev-daps-cert-consumer-key"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/cert.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-dev-daps-cert-consumer"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/cert.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-dev-daps-cert-provider"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/key.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-dev-daps-cert-provider-key"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/cert.json "{{ $vaultUrl }}/v1/traceability-irs/data/dev-provider2-cert"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/key.json "{{ $vaultUrl }}/v1/traceability-irs/data/dev-provider2-key"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/cert.json "{{ $vaultUrl }}/v1/traceability-irs/data/dev-provider3-cert"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/key.json "{{ $vaultUrl }}/v1/traceability-irs/data/dev-provider3-key"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/cert.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-int-daps-cert"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
               --post-file=/opt/config/key.json "{{ $vaultUrl }}/v1/traceability-irs/data/irs-int-daps-key"

              /bin/vault kv put traceability-irs/test-edc-encryption-key content=<path:traceability-irs/data/test-edc-encryption-key#content>
              /bin/vault kv put traceability-irs/dev-provider1-miw-secret content=<path:traceability-irs/data/dev-provider1-miw-secret#content>
              /bin/vault kv put traceability-irs/dev-provider2-miw-secret content=<path:traceability-irs/data/dev-provider2-miw-secret#content>
              /bin/vault kv put traceability-irs/dev-provider3-miw-secret content=<path:traceability-irs/data/dev-provider3-miw-secret#content>
              /bin/vault kv put traceability-irs/dil-consumer-miw-secret content=<path:traceability-irs/data/dil-consumer-miw-secret#content>
              /bin/vault kv put traceability-irs/edc-test-miw-keycloak-secret content=<path:traceability-irs/data/edc-test-miw-keycloak-secret#content>
              /bin/vault kv put traceability-irs/miw-dev-keycloak-secret content=<path:traceability-irs/data/miw-dev-keycloak-secret#content>
              /bin/vault kv put traceability-irs/miw-ess-keycloak-secret content=<path:traceability-irs/data/miw-ess-keycloak-secret#content>
              /bin/vault kv put traceability-irs/miw-ess-provider-keycloak-secret content=<path:traceability-irs/data/miw-ess-provider-keycloak-secret#content>
              /bin/vault kv put traceability-irs/miw-int-keycloak-secret content=<path:traceability-irs/data/miw-int-keycloak-secret#content>
              /bin/vault kv put traceability-irs/miw-pen-keycloak-secret content=<path:traceability-irs/data/miw-pen-keycloak-secret#content>
              /bin/vault kv put traceability-irs/dim-secret-dev content=<path:traceability-irs/data/dim-secret-dev#content>

          volumeMounts:
            - name: config-volume
              mountPath: /opt/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ $fullName }}-vault-edc-configmap
            defaultMode: 0777



