{{- if .Values.semanticsHub.localModels }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "irs.fullname" . }}-configmap-semantic-models
  namespace: {{ .Values.namespace }}
binaryData:
  {{- tpl (toYaml .Values.semanticsHub.localModels) . | nindent 2 }}
{{- end }}
