{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "irs.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "irs.name" . }}
    chart: {{ template "irs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  minioUser: {{ .Values.minioUser | default "minio" | b64enc | quote }}
  minioPassword: {{ .Values.minioPassword | default "minio" | b64enc | quote }}
  keycloakClientId: {{ .Values.keycloak.oauth2.clientId | default "keycloakClientId" | b64enc | quote }}
  keycloakClientSecret: {{ .Values.keycloak.oauth2.clientSecret | default "keycloakClientSecret" | b64enc | quote }}
  edcApiSecret: {{ .Values.edc.controlplane.apikey.secret | default "" | b64enc | quote }}
  {{- if .Values.grafana.enabled }}
  grafanaUser: {{ .Values.grafana.user | default "grafana" | b64enc | quote }}
  grafanaPassword: {{ .Values.grafana.password | default "grafana" | b64enc | quote }}
  {{- end }}
{{- end }}
