tractusx-connector:

  controlplane:
    # SSI configuration
    ssi:
      oauth:
        client:
          id: <path:traceability-irs/data/dev/controlplane#ssi.oauth.client.id.provider3>
          secretAlias: dev-provider3-miw-secret
    ingresses:
      - enabled: true
        hostname: "irs-provider-controlplane3.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

  dataplane:
    ingresses:
      - enabled: true
        hostname: "irs-provider-dataplane3.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

  backendService:
    httpProxyTokenReceiverUrl: "https://irs-submodel-server.dev.demo.catena-x.net/data/endpoint-data-reference-provider3"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: dev-provider3-key
      transferProxyTokenSignerPublicKey: dev-provider3-cert
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key

  postgresql:
    jdbcUrl: "jdbc:postgresql://irs-provider3-edc-postgresql-hl:5432/edc"
