tractusx-connector:
  participant:
    id: BPNL00000003CRHK

  controlplane:
    ingresses:
      - enabled: true
        hostname: "irs-provider-controlplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

  dataplane:
    ingresses:
      - enabled: true
        hostname: "irs-provider-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

  backendService:
    httpProxyTokenReceiverUrl: "https://irs-submodel-server.dev.demo.catena-x.net/data/endpoint-data-reference-provider1"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: irs-dev-daps-cert-provider-key
      transferProxyTokenSignerPublicKey: irs-dev-daps-cert-provider
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key
      dapsPrivateKey: irs-dev-daps-cert-provider-key
      dapsPublicKey: irs-dev-daps-cert-provider

  daps:
    clientId: <path:traceability-irs/data/dev/controlplane#edc.oauth.client.id-provider1>

  postgresql:
    jdbcUrl: "jdbc:postgresql://irs-provider-edc-postgresql-hl:5432/edc"
