tractusx-connector:
  iatp:
    sts:
      oauth:
        client:
          id: <path:traceability-irs/data/ess/controlplane#ssi.oauth.client.id.provider>
          secret_alias: miw-ess-provider-keycloak-secret

  controlplane:
    ingresses:
      - enabled: true
        hostname: "irs-ess-provider-controlplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

    resources:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi

  dataplane:
    token:
      signer:
        privatekey_alias: irs-dev-daps-cert-provider-key
      verifier:
        publickey_alias: irs-dev-daps-cert-provider

    ingresses:
      - enabled: true
        hostname: "irs-ess-provider-dataplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi

  vault:
    hashicorp:
      healthCheck:
        enabled: false
    secretNames:
      transferProxyTokenSignerPrivateKey: irs-dev-daps-cert-provider-key
      transferProxyTokenSignerPublicKey: irs-dev-daps-cert-provider
      transferProxyTokenEncryptionAesKey: test-edc-encryption-key

  postgresql:
    jdbcUrl: "jdbc:postgresql://ess-provider-edc-postgresql-hl:5432/edc"
