name: Deploy to ArgoCD

on:
  push:
  workflow_dispatch: # Trigger manually
    input:
      environment:
        type: choice
        options:
          - 'dev'
          - 'int'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment
        run: |
          echo "ARGOCD_ENV=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV

      - name: Set secrets for DEV
        if: github.event.inputs.environment == null || github.event.inputs.environment == 'dev'
        run: |
          echo "ARGOCD_TOKEN=${{ secrets.ARGOCD_TOKEN_DEV }}" >> $GITHUB_ENV

      - name: Set secrets for INT
        if: github.event.inputs.environment == 'int'
        run: echo "ARGOCD_TOKEN=${{ secrets.ARGOCD_TOKEN_INT }}" >> $GITHUB_ENV

      - name: Deploy new app
        run: >
          curl
          --request POST 
          -H "Content-Type: application/json"
          -H "Authorization: Bearer ${{ env.ARGOCD_TOKEN }}"
          --url "https://argo.${{ env.ARGOCD_ENV }}.demo.catena-x.net/api/v1/applications?upsert=true"
          --data-binary "@charts/irs-environments/${{ env.ARGOCD_ENV }}/argo-app.json"
