name: Deploy to ArgoCD

on:
  workflow_dispatch: # Trigger manually
    input:
      environment:
        type: choice
        options:
          - 'dev'
          - 'int'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          curl 
          --request POST 
          -H "Content-Type: application/json"
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
          --url https://argo.dev.demo.catena-x.net/api/v1/applications
          --data-binary "@charts/irs-environments/dev/argo-app.json"
