name: Release Helm Charts

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release-helm-charts:
    strategy:
      matrix:
        chart:
          - irs-helm
          - edc-consumer
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get helm charts latest tag version
        id: step1
        run: |
          latestVersion=$(git tag | grep "${{ matrix.chart }}-[1-9]" | tail -1 | sed 's/.*-//g')
          echo "latest_version=$latestVersion" >> $GITHUB_OUTPUT
          echo "Exported $latestVersion latest helm charts version"
      - name: Get helm charts current version
        id: step2
        run: |
          chartVersion=$(cat ./charts/${{ matrix.chart }}/Chart.yaml | grep "version:" | head -1 | cut -d ":" -d " " -f2)
          echo "current_version=$chartVersion" >> $GITHUB_OUTPUT
          echo "Exported $chartVersion helm charts version"

      - name: Install Helm
        if: steps.step1.outputs.latest_version != steps.step2.outputs.current_version
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Update helm dependencies
        if: steps.step1.outputs.latest_version != steps.step2.outputs.current_version
        run: |
          cd charts/${{ matrix.chart }}
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add minio https://charts.min.io/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm dependency update

      - name: Run chart-releaser
        if: steps.step1.outputs.latest_version != steps.step2.outputs.current_version
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts/${{ matrix.chart }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
