name: IRS INT Cucumber Integration test execution

on:
  workflow_dispatch: # Trigger manually

jobs:
  trigger-integration-test:
    uses: ./.github/workflows/xray-cucumber-integration.yaml
    secrets:
      keycloakTokenUrl: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI }}
      clientId: ${{ secrets.ORG_IRS_OAUTH2_CLIENT_ID_INT }}
      clientSecret: ${{ secrets.ORG_IRS_OAUTH2_CLIENT_SECRET_INT }}
      jiraUser: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
      jiraPassword: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
    with:
      executionFilter: "not @Ignore and @INTEGRATION_TEST and @INT"
      exportFilter: "11349"

