name: Update DEV and INT after Helm release

on:
  workflow_dispatch:
  push:
    tags:
      - "irs-helm-*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        uses: mikefarah/yq@v4.33.3

      - name: Define new Helm version
        run: echo NEW_HELM_VERSION=$(echo ${{ github.ref_name }} | sed -n 's/.*\([0-9]\+.[0-9]\+.[0-9]\+\)/\1/p') >> $GITHUB_ENV

      - name: Update DEV
        run: |
          CURRENT_VERSION=$(yq eval '.version' charts/irs-environments/dev/Chart.yaml)
          NEXT_VERSION=$(echo $CURRENT_VERSION | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')
          yq -i eval ".version = \"$NEXT_VERSION\"" charts/irs-environments/dev/Chart.yaml
          yq -i eval ".dependencies[0].version = \"$NEW_HELM_VERSION\"" charts/irs-environments/dev/Chart.yaml

      - name: Update INT
        run: |
          CURRENT_VERSION=$(yq eval '.version' charts/irs-environments/int/Chart.yaml)
          NEXT_VERSION=$(echo $CURRENT_VERSION | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')
          yq -i eval ".version = \"$NEXT_VERSION\"" charts/irs-environments/int/Chart.yaml
          yq -i eval ".dependencies[0].version = \"$NEW_HELM_VERSION\"" charts/irs-environments/int/Chart.yaml

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(env): Update environments after Helm release"
          branch: chore/update-environments-${{ github.ref_name }}
          base: catena-x-environments
          delete-branch: true
          title: "Update DEV and INT to next release version"
          body: "This PR updates the DEV and INT deployments to the new recently released Helm version."
